export const designTokens = {
  colors: {
    background: "var(--color-background)",
    foreground: "var(--color-foreground)",
    muted: "var(--color-muted)",
    mutedForeground: "var(--color-muted-foreground)",
    surface: "var(--color-surface)",
    surfaceSubtle: "var(--color-surface-subtle)",
    border: "var(--color-border)",
    borderStrong: "var(--color-border-strong)",
    inverse: "var(--color-inverse)",
    inverseForeground: "var(--color-inverse-foreground)",
    focus: "var(--color-focus)",
  },
  spacing: {
    0: "var(--space-0)",
    1: "var(--space-1)",
    2: "var(--space-2)",
    3: "var(--space-3)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    8: "var(--space-8)",
    10: "var(--space-10)",
    12: "var(--space-12)",
    16: "var(--space-16)",
    20: "var(--space-20)",
    pageY: "var(--space-page-y)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
  },
  shadow: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
  },
  typography: {
    display: "text-4xl font-semibold tracking-tight sm:text-5xl",
    h1: "text-3xl font-semibold tracking-tight sm:text-4xl",
    h2: "text-2xl font-semibold tracking-tight sm:text-3xl",
    h3: "text-xl font-semibold tracking-tight sm:text-2xl",
    h4: "text-lg font-semibold tracking-tight",
    body: "text-base leading-7",
    small: "text-sm leading-6",
    caption: "text-xs leading-5",
  },
  transition: {
    colors: "color 150ms ease, background-color 150ms ease, border-color 150ms ease",
  },
  zIndex: {
    header: "var(--z-header)",
    overlay: "var(--z-overlay)",
  },
  containers: {
    sm: "var(--container-sm)",
    md: "var(--container-md)",
    lg: "var(--container-lg)",
    xl: "var(--container-xl)",
    "2xl": "var(--container-2xl)",
  },
} as const;
